services:
  # DB and INFRA components
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - quant_net
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
       POSTGRES_DB: quanttrade
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    container_name: quant-redis
    command: redis-server --save "" --appendonly no
    ports:
      - "6379:6379"
    networks:
      - quant_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 2s

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"   
      - "15672:15672" 
    networks:
      - quant_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

# MICROSERVICES
  api-gateway:
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    networks:
      - quant_net
    environment:
      AUTH_SERVICE_URL: http://auth-service:3006
      MARKET_DATA_URL: http://market-data-service:3001
      QUANT_ENGINE_URL: http://quant-ai-engine:3002
      EXECUTION_SERVICE_URL: http://execution-service:3003
    depends_on:
      - auth-service
      - market-data-service
      - quant-ai-engine
      - execution-service
    restart: unless-stopped


  execution-service:
    build:
      context: ./execution-service/
      dockerfile: Dockerfile
    container_name: execution-service
    ports:
      - "3003:3003"
    networks:
      - quant_net
    environment:
      DB_URL: postgres://postgres:password@postgres:5432/quanttrade
      RABBITMQ_URL: amqp://rabbitmq:5672
      QUANT_ENGINE_URL: http://quant-ai-engine:3002
    depends_on:
      - postgres
      - quant-ai-engine
      - rabbitmq
    restart: unless-stopped


  market-data-service:
    build:
      context: ./market-data-service/
      dockerfile: Dockerfile
    container_name: market-data-service
    ports:
      - "3001:3001"
    networks:
      - quant_net
    volumes:
      - redis_data:/market-data-service
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped


  notification-service:
    build:
      context: ./notification-service/
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "3004:3004"
    networks:
      - quant_net
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped


  quant-ai-engine: 
    build:
      context: ./quant-ai-engine/
      dockerfile: Dockerfile
    container_name: quant-engine
    ports:
      - "3002:3002"
    networks:
      - quant_net
    volumes:
      - redis_data:/quant-ai-engine
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
  
  producer:
    build:
      context: ./producer/
      dockerfile: Dockerfile
    container_name: quant-producer
    environment:
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
    networks:
      - quant_net
    depends_on:
      redis:
        condition: service_healthy
  consumer:
    build:
      context: ./consumer/
      dockerfile: Dockerfile
    container_name: quant_consumer
    ports:
      - "3005:8000"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - quant_net

  execution-engine:
    build:
      context: ./consumer/
      dockerfile: ex.en.Dockerfile
    container_name: execution-engine
    networks:
      - quant_net
    environment:
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      redis:
        condition: service_healthy
      consumer:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  auth-service:
    build:
      context: ./auth-service/
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3006:3006"
    networks:
      - quant_net
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/quanttrade
      JWT_SECRET_KEY: yash27
      JWT_EXPIRE_MINUTES: 15
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006/health"] 
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
  pg_data:
networks:
  quant_net:
