apiVersion: v1
kind: Service
metadata:
  name: {{ include "market-data-service.fullname" . }}
  labels:
    {{- include "market-data-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: market-data-port
  selector:
    {{- include "market-data-service.selectorLabels" . | nindent 4 }}
