apiVersion: v1
kind: Service
metadata:
  name: {{ include "quant-ai-engine.fullname" . }}
  labels:
    {{- include "quant-ai-engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: quant-engine-port
  selector:
    {{- include "quant-ai-engine.selectorLabels" . | nindent 4 }}
