name: Execution Service CI Pipeline

on:
  push:
    branches:
      - test
      - main
    paths:
      - "execution-service/**"
      - "helm/charts/execution-service/**"
      - ".github/workflows/execution-ci.yml"
  pull_request:
    branches:
      - main


jobs:
  Code-Review:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Credentials HardCoding Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GAT }}


  Image-Build-Scan-Push-To-Registry:
    runs-on: ubuntu-latest
    needs: Code-Review
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Image Build
        uses: docker/build-push-action@v5
        with:
          context: "./execution-service"
          load: True
          tags: quant-execution-service:${{github.sha}}
      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'quant-execution-service:${{github.sha}}'
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL"
      - name: Push To DockerHub
        run: |
          docker tag quant-execution-service:${{github.sha}} ${{ secrets.DOCKER_USERNAME }}/quant-execution-service:${{github.sha}}

          docker push ${{ secrets.DOCKER_USERNAME }}/quant-execution-service:${{github.sha}}
  Helm:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [Code-Review,Image-Build-Scan-Push-To-Registry]
    concurrency:
      group: CI-push-queue  
      cancel-in-progress: false
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GAT }}

      - name: Update Helm Values
        run: |

          yq -i '.image.repository = "${{ secrets.DOCKER_USERNAME }}/quant-execution-service"' helm/charts/execution-service/values.yaml
          yq -i '.image.tag = "${{github.sha}}"' helm/charts/execution-service/values.yaml
          cat helm/charts/execution-service/values.yaml

      - name: Commit and Push Changes to Trigger ArgoCD
        run: |
          git config user.name "${{ secrets.GUN }}"
          git config user.email "${{ secrets.GMAIL }}"
          git add helm/charts/execution-service/values.yaml
          git commit -m "chore(gitops): update execution-service image to ${{github.sha}} [skip ci]"
          git pull --rebase origin ${{ github.ref_name }}
          git push -u origin ${{ github.ref_name }}
